In [2]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, recall_score, precision_score
from collections import Counter
import pandas as pd
import numpy as np
''' Summary of the file.

    功能：
        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以KNN方法划分并获得准确率，通过混淆矩阵标示结果。

    输出：
        结果的混淆矩阵，每次划分的准确率，十次的平均准确率
'''



' Summary of the file.\n\n    功能：\n        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以KNN方法划分并获得准确率，通过混淆矩阵标示结果。\n\n    输出：\n        结果的混淆矩阵，每次划分的准确率，十次的平均准确率\n'

In [3]:
# 实验室的15000条恶意样本，分为十个家族


# LBP_block
subfeatures=pd.read_csv(r'E:\test\process_lpb_block\feature_train_full.csv',header=None)
labels = pd.read_csv(r'E:\test\process_lpb_block\CNO_full.txt',header=None)

# # LBP特征值
# subfeatures=pd.read_csv(r'E:\test\process_lpb\feature_train_full.csv',header=None)
# labels = pd.read_csv(r'E:\test\process_lpb\CNO_full.txt',header=None)

'''
# # GIST特征值
subfeatures=pd.read_csv(r'E:\test\process_gist\gist_f_train_full.csv',header=None)
labels = pd.read_csv(r'E:\test\process_gist\CNO_full.txt',header=None)
'''
# # text段代码提取二进制代码，生成图像的LBP特征
# subfeatures=pd.read_csv('/home/stack/Data/Output/lbp_only_text/feature_train_full.csv',header=None)
# labels = pd.read_csv('/home/stack/Data/Output/lbp_only_text/CNO_full.txt',header=None)

# text段 GIST特征
##subfeatures=pd.read_csv(r'E:\test\process_gist\gist_f_train_full.csv',header=None)
##labels = pd.read_csv(r'E:\test\process_gist\CNO_full.txt',header=None)


FileNotFoundError: [Errno 2] File b'E:\\test\\process_lpb_block\\feature_train_full.csv' does not exist: b'E:\\test\\process_lpb_block\\feature_train_full.csv'

In [ ]:
#subfeatures.fillna('0')


# 平均准确率归零
avgscore = 0
recallscore = 0
precisionscore = 0
N = 10




In [ ]:
# 以10%的比例进行交叉验证
#X_train, X_test, y_train, y_test = cross_validation.train_test_split(subfeatures, features_labels, test_size=0.1)
X_train, X_test, y_train, y_test = train_test_split(subfeatures, labels, test_size=0.1)

#print(y_train)




In [ ]:
# 进行训练
print('train...')
# 进行KNN训练,距离为1
neigh = KNeighborsClassifier(n_neighbors=1)
neigh.fit(X_train, y_train)


In [ ]:
# 预试
print('test...')
c_test = neigh.predict(X_test)

#print(y_test)
#print(c_test)

In [7]:
# 计算预测划分准确率
print('accurary...')
score = neigh.score(X_test, y_test)
print(classification_report(y_test,c_test))
avgscore = avgscore + score
recallscore = recallscore + recall_score(y_test,c_test,average="macro")
precisionscore = precisionscore + precision_score(y_test,c_test,average="macro")
print(score)



accurary...
              precision    recall  f1-score   support

           1       0.75      0.61      0.67       137
           2       0.91      0.86      0.89       136
           3       0.88      0.78      0.83       125
           4       0.97      0.99      0.98       156
           5       0.97      0.97      0.97       149
           6       0.98      0.99      0.99       167
           7       0.95      0.91      0.93       147
           8       0.69      0.99      0.81       142
           9       0.95      0.89      0.92       151
          10       0.94      0.91      0.93       147

   micro avg       0.90      0.90      0.90      1457
   macro avg       0.90      0.89      0.89      1457
weighted avg       0.90      0.90      0.90      1457

0.8970487302676733


In [8]:
# 通过混淆矩阵进行结果标示
cm = confusion_matrix(y_test, c_test)
np.set_printoptions(threshold=10000)
np.set_printoptions(precision=2)
print('Confusion matrix, without normalization')
print(str(cm))


Confusion matrix, without normalization
[[ 83   5   5   0   1   0   6  30   3   4]
 [  4 117   2   0   0   0   0  13   0   0]
 [  8   2  98   0   1   0   0  13   1   2]
 [  0   0   0 155   0   0   0   0   1   0]
 [  2   0   0   0 145   2   0   0   0   0]
 [  1   0   0   0   0 166   0   0   0   0]
 [  3   2   3   0   1   0 134   3   1   0]
 [  1   0   0   0   0   0   0 141   0   0]
 [  5   1   3   4   1   1   0   0 134   2]
 [  3   1   1   0   1   0   1   5   1 134]]


In [9]:
# 进行十次KNN测试
for i in range(N):
    # 以10%的比例进行交叉验证
    #X_train, X_test, y_train, y_test = cross_validation.train_test_split(subfeatures, features_labels, test_size=0.1)
    X_train, X_test, y_train, y_test = train_test_split(subfeatures, labels, test_size=0.1)

    # 进行训练
    print('train...')
    # 进行KNN训练,距离为1
    neigh = KNeighborsClassifier(n_neighbors=1)
    neigh.fit(X_train, y_train)

    # 预试
    print('test...')
    c_test = neigh.predict(X_test)

    # print(y_test)
    # print(c_test)

    # 计算预测划分准确率
    print('accurary...')
    score = neigh.score(X_test, y_test)
    print(classification_report(y_test,c_test))
    avgscore = avgscore + score
    recallscore = recallscore + recall_score(y_test,c_test,average="macro")
    precisionscore = precisionscore + precision_score(y_test,c_test,average="macro")
    print(score)

    # 通过混淆矩阵进行结果标示
    cm = confusion_matrix(y_test, c_test)
    np.set_printoptions(threshold=10000)
    np.set_printoptions(precision=2)
    print('Confusion matrix, without normalization\n')
    print(str(cm))


train...


E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.45      0.78      0.57       149
           2       0.95      0.84      0.89       154
           3       0.82      0.73      0.77       129
           4       0.99      1.00      0.99       162
           5       0.99      0.99      0.99       151
           6       0.97      0.99      0.98       143
           7       0.94      0.91      0.92       137
           8       0.96      0.48      0.64       157
           9       0.93      0.92      0.92       136
          10       0.94      0.94      0.94       139

   micro avg       0.86      0.86      0.86      1457
   macro avg       0.89      0.86      0.86      1457
weighted avg       0.89      0.86      0.86      1457

0.8565545641729582
Confusion matrix, without normalization
[[116   1  12   0   1   2   6   2   4   5]
 [ 21 129   2   0   0   0   0   0   2   0]
 [ 26   5  94   0   0   0   0   1   3   0]
 [  0   0   0 162   0   0   0   0

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.47      0.82      0.60       153
           2       0.97      0.79      0.87       151
           3       0.86      0.78      0.82       123
           4       0.98      1.00      0.99       149
           5       0.99      1.00      1.00       155
           6       1.00      0.99      1.00       163
           7       0.96      0.90      0.93       143
           8       0.96      0.50      0.65       147
           9       0.88      0.93      0.91       132
          10       0.94      0.92      0.93       141

   micro avg       0.87      0.87      0.87      1457
   macro avg       0.90      0.86      0.87      1457
weighted avg       0.90      0.87      0.87      1457

0.8654770075497598
Confusion matrix, without normalization
[[126   4   8   0   1   0   2   1   6   5]
 [ 27 119   2   0   0   0   1   1   1   0]
 [ 17   0  96   0   0   0   2   1   6   1]
 [  0   0   0 149   0   0   0   0

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.78      0.64      0.70       151
           2       0.94      0.81      0.87       176
           3       0.75      0.79      0.77       100
           4       0.97      0.99      0.98       148
           5       0.98      0.99      0.99       139
           6       0.99      1.00      1.00       147
           7       0.89      0.89      0.89       142
           8       0.74      1.00      0.85       152
           9       0.97      0.88      0.92       145
          10       0.94      0.94      0.94       157

   micro avg       0.89      0.89      0.89      1457
   macro avg       0.90      0.89      0.89      1457
weighted avg       0.90      0.89      0.89      1457

0.8943033630748113
Confusion matrix, without normalization
[[ 96   6  14   0   2   0   8  21   0   4]
 [  6 143   3   0   0   0   1  22   1   0]
 [  7   1  79   0   0   0   2   7   2   2]
 [  0   0   1 147   0   0   0   0

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.79      0.65      0.71       152
           2       0.96      0.87      0.91       145
           3       0.83      0.72      0.77       103
           4       0.99      0.99      0.99       145
           5       0.98      0.99      0.99       142
           6       0.99      1.00      1.00       171
           7       0.95      0.89      0.92       145
           8       0.68      0.96      0.80       145
           9       0.94      0.93      0.93       155
          10       0.94      0.96      0.95       154

   micro avg       0.90      0.90      0.90      1457
   macro avg       0.91      0.90      0.90      1457
weighted avg       0.91      0.90      0.90      1457

0.9025394646533974
Confusion matrix, without normalization
[[ 99   1   5   0   2   0   1  37   3   4]
 [  3 126   1   0   0   0   1  14   0   0]
 [ 10   2  74   0   0   1   3  10   3   0]
 [  0   0   0 144   0   0   0   0

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.83      0.69      0.75       150
           2       0.96      0.85      0.90       132
           3       0.87      0.80      0.84       117
           4       0.98      1.00      0.99       160
           5       0.99      0.99      0.99       142
           6       0.99      1.00      0.99       152
           7       0.94      0.87      0.90       156
           8       0.68      1.00      0.81       141
           9       0.94      0.88      0.91       160
          10       0.95      0.95      0.95       147

   micro avg       0.91      0.91      0.91      1457
   macro avg       0.91      0.90      0.90      1457
weighted avg       0.91      0.91      0.91      1457

0.9052848318462594
Confusion matrix, without normalization
[[103   3   7   0   0   0   2  30   1   4]
 [  3 112   0   0   0   0   0  17   0   0]
 [  7   0  94   0   0   1   1  12   2   0]
 [  0   0   0 160   0   0   0   0

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.46      0.85      0.60       136
           2       0.98      0.83      0.90       146
           3       0.90      0.73      0.80       131
           4       0.98      1.00      0.99       160
           5       0.98      1.00      0.99       154
           6       0.98      0.99      0.99       166
           7       0.94      0.91      0.92       149
           8       0.89      0.48      0.62       138
           9       0.93      0.89      0.91       141
          10       0.93      0.93      0.93       136

   micro avg       0.87      0.87      0.87      1457
   macro avg       0.90      0.86      0.87      1457
weighted avg       0.90      0.87      0.87      1457

0.8675360329444063
Confusion matrix, without normalization
[[115   2   5   0   1   1   2   2   3   5]
 [ 20 121   1   0   0   0   1   3   0   0]
 [ 23   0  95   0   2   2   2   2   2   3]
 [  0   0   0 160   0   0   0   0

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.83      0.61      0.70       161
           2       0.95      0.88      0.91       169
           3       0.86      0.77      0.81       110
           4       0.97      0.99      0.98       145
           5       0.98      1.00      0.99       155
           6       0.99      0.98      0.98       144
           7       0.93      0.92      0.92       153
           8       0.65      1.00      0.79       129
           9       0.93      0.88      0.90       134
          10       0.92      0.93      0.92       157

   micro avg       0.90      0.90      0.90      1457
   macro avg       0.90      0.90      0.89      1457
weighted avg       0.91      0.90      0.89      1457

0.8956760466712422
Confusion matrix, without normalization
[[ 98   3  10   0   1   0   5  31   4   9]
 [  5 148   0   0   0   0   1  15   0   0]
 [  5   3  85   0   1   0   3  11   1   1]
 [  0   0   0 144   0   0   0   0

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.78      0.65      0.71       147
           2       0.94      0.83      0.88       138
           3       0.83      0.77      0.80       125
           4       0.99      0.99      0.99       128
           5       0.99      0.99      0.99       171
           6       0.99      0.98      0.98       134
           7       0.91      0.89      0.90       138
           8       0.96      0.53      0.68       149
           9       0.95      0.90      0.93       176
          10       0.51      0.95      0.66       151

   micro avg       0.85      0.85      0.85      1457
   macro avg       0.89      0.85      0.85      1457
weighted avg       0.89      0.85      0.85      1457

0.849691146190803
Confusion matrix, without normalization
[[ 95   2   8   0   0   0   4   1   2  35]
 [  4 114   0   0   0   0   1   1   0  18]
 [  9   2  96   0   1   0   1   1   2  13]
 [  0   0   0 127   0   0   1   0 

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.86      0.62      0.72       152
           2       0.97      0.80      0.88       153
           3       0.81      0.79      0.80       120
           4       0.98      1.00      0.99       163
           5       0.98      0.99      0.99       122
           6       0.99      1.00      0.99       160
           7       0.94      0.90      0.92       169
           8       0.66      0.99      0.79       149
           9       0.92      0.89      0.91       130
          10       0.95      0.96      0.96       139

   micro avg       0.90      0.90      0.90      1457
   macro avg       0.91      0.90      0.89      1457
weighted avg       0.91      0.90      0.90      1457

0.8963623884694578
Confusion matrix, without normalization
[[ 94   2  11   0   2   0   6  30   4   3]
 [  4 123   0   0   0   0   0  24   1   1]
 [  6   1  95   0   0   1   3  10   3   1]
 [  0   0   0 163   0   0   0   0

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.78      0.65      0.71       145
           2       0.97      0.80      0.88       158
           3       0.84      0.76      0.80        99
           4       0.98      1.00      0.99       158
           5       0.99      0.99      0.99       149
           6       0.98      0.99      0.99       141
           7       0.94      0.93      0.93       161
           8       0.67      0.99      0.80       134
           9       0.95      0.90      0.93       153
          10       0.91      0.92      0.92       159

   micro avg       0.90      0.90      0.90      1457
   macro avg       0.90      0.89      0.89      1457
weighted avg       0.91      0.90      0.90      1457

0.8984214138641043
Confusion matrix, without normalization
[[ 94   2   5   0   0   0   4  32   2   6]
 [  9 127   1   0   0   0   0  20   0   1]
 [  6   0  75   0   0   1   3   8   3   3]
 [  0   0   0 158   0   0   0   0

In [10]:
# 输出N次的平均准确率
avgscore = avgscore / N
recallscore = recallscore / N
precisionscore = precisionscore / N

print('avgscore....')
print(avgscore)
print('False positive rate')
print(1-precisionscore)
print('false negative rate')
print(1-recallscore)

avgscore....
0.9728894989704873
False positive rate
0.009901211845874003
false negative rate
0.03009934945647963
