In [7]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, recall_score, precision_score
from collections import Counter
import pandas as pd
import numpy as np
''' Summary of the file.

    功能：
        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以KNN方法划分并获得准确率，通过混淆矩阵标示结果。

    输出：
        结果的混淆矩阵，每次划分的准确率，十次的平均准确率
'''



' Summary of the file.\n\n    功能：\n        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以KNN方法划分并获得准确率，通过混淆矩阵标示结果。\n\n    输出：\n        结果的混淆矩阵，每次划分的准确率，十次的平均准确率\n'

In [8]:
# 实验室的15000条恶意样本，分为十个家族
# # LBP特征值
subfeatures=pd.read_csv(r'F:\virtus_test\Simhash_LBP\feature_train_full.csv',header=None)
labels = pd.read_csv(r'F:\virtus_test\Simhash_LBP\CNO_full.txt',header=None)

'''
# # GIST特征值
subfeatures=pd.read_csv(r'E:\test\process_gist\gist_f_train_full.csv',header=None)
labels = pd.read_csv(r'E:\test\process_gist\CNO_full.txt',header=None)
'''
# # text段代码提取二进制代码，生成图像的LBP特征
# subfeatures=pd.read_csv('/home/stack/Data/Output/lbp_only_text/feature_train_full.csv',header=None)
# labels = pd.read_csv('/home/stack/Data/Output/lbp_only_text/CNO_full.txt',header=None)

# text段 GIST特征
##subfeatures=pd.read_csv(r'E:\test\process_gist\gist_f_train_full.csv',header=None)
##labels = pd.read_csv(r'E:\test\process_gist\CNO_full.txt',header=None)


"\n# # GIST特征值\nsubfeatures=pd.read_csv(r'E:\test\\process_gist\\gist_f_train_full.csv',header=None)\nlabels = pd.read_csv(r'E:\test\\process_gist\\CNO_full.txt',header=None)\n"

In [9]:
# 删除数据量较小的数据
result = pd.concat([subfeatures, labels], axis=1,ignore_index=True)
'''
print(result)
print(result.apply(lambda x: x.sum(), axis=1))
print(labels.apply(lambda x: x.sum(), axis=1))
print(labels.apply(lambda x: x.sum(), axis=1)==result.apply(lambda x: x.sum(), axis=1))
'''
list=[]
Q = result.apply(lambda x: x.sum(), axis=1)
# W = labels.apply(lambda x: x.sum(), axis=1)
for t in range(len(result)):
    if Q[t] <= 2.5:
        list.append(t)
# print(list,len(list))  #打印出较小数据量的标号和个数
result=result.drop(labels=list,axis=0)

subfeatures=result.iloc[:,:-1]
labels=result.iloc[:,-1]
print (subfeatures)

            0         1         2         3         4         5         6    \
1479   0.004464  0.000325  0.001411  0.000186  0.000202  0.000047  0.000140   
1480   0.004464  0.000325  0.001411  0.000186  0.000202  0.000047  0.000140   
1481   0.004464  0.000325  0.001411  0.000186  0.000202  0.000047  0.000140   
1482   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1483   0.004464  0.000325  0.001411  0.000186  0.000202  0.000047  0.000140   
1484   0.004464  0.000325  0.001411  0.000186  0.000202  0.000047  0.000140   
1485   0.004464  0.000325  0.001411  0.000186  0.000202  0.000047  0.000140   
1486   0.001674  0.000186  0.000558  0.000062  0.000016  0.000000  0.000031   
1487   0.004464  0.000325  0.001411  0.000186  0.000202  0.000047  0.000140   
1488   0.004464  0.000325  0.001411  0.000186  0.000202  0.000047  0.000140   
1489   0.003751  0.000418  0.001457  0.000155  0.000263  0.000062  0.000108   
1490   0.004464  0.000325  0.001411  0.000186  0.000

In [10]:
#subfeatures.fillna('0')


# 平均准确率归零
avgscore = 0
recallscore = 0
precisionscore = 0
N = 10




In [ ]:
# 进行十次KNN测试
for i in range(N):
    # 以10%的比例进行交叉验证
    # X_train, X_test, y_train, y_test = cross_validation.train_test_split(subfeatures, features_labels, test_size=0.1)
    X_train, X_test, y_train, y_test = train_test_split(subfeatures, labels, test_size=0.1)

    # 进行训练
    print('train...')
    # 进行KNN训练,距离为1
    neigh = KNeighborsClassifier(n_neighbors=1)
    neigh.fit(X_train, y_train)

    # 预试
    print('test...')
    c_test = neigh.predict(X_test)

    # print(y_test)
    # print(c_test)

    # 计算预测划分准确率
    print('accurary...')
    score = neigh.score(X_test, y_test)
    print(classification_report(y_test,c_test))
    avgscore = avgscore + score
    recallscore = recallscore + recall_score(y_test,c_test,average="macro")
    precisionscore = precisionscore + precision_score(y_test,c_test,average="macro")
    print(score)

    # 通过混淆矩阵进行结果标示
    cm = confusion_matrix(y_test, c_test)
    np.set_printoptions(threshold=10000)
    np.set_printoptions(precision=2)
    print('Confusion matrix, without normalization\n')
    print(str(cm))

train...
test...
accurary...
              precision    recall  f1-score   support

           2       0.92      0.78      0.84       154
           3       0.43      0.91      0.59       145
           4       1.00      0.98      0.99       158
           5       0.98      0.92      0.95       136
           6       0.94      0.99      0.96       150
           7       0.94      0.91      0.93       150
           8       0.98      0.29      0.45       147
           9       0.93      0.88      0.90       145
          10       0.95      0.84      0.89       142

   micro avg       0.83      0.83      0.83      1327
   macro avg       0.90      0.83      0.83      1327
weighted avg       0.90      0.83      0.84      1327

0.8342125094197438
Confusion matrix, without normalization

[[120  28   0   0   0   4   0   2   0]
 [  5 132   0   0   0   3   1   1   3]
 [  0   3 155   0   0   0   0   0   0]
 [  0   2   0 125   8   0   0   0   1]
 [  0   2   0   0 148   0   0   0   0]
 [  2   5  

In [ ]:
# 输出N次的平均准确率
avgscore = avgscore / N
recallscore = recallscore / N
precisionscore = precisionscore / N

print('avgscore....')
print(avgscore)
print('False positive rate')
print(1-precisionscore)
print('false negative rate')
print(1-recallscore)