In [29]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, recall_score, precision_score
from collections import Counter
import pandas as pd
import numpy as np
''' Summary of the file.

    功能：
        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以KNN方法划分并获得准确率，通过混淆矩阵标示结果。

    输出：
        结果的混淆矩阵，每次划分的准确率，十次的平均准确率
'''



' Summary of the file.\n\n    功能：\n        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以KNN方法划分并获得准确率，通过混淆矩阵标示结果。\n\n    输出：\n        结果的混淆矩阵，每次划分的准确率，十次的平均准确率\n'

In [30]:
# 实验室的15000条恶意样本，分为十个家族
# # LBP特征值
subfeatures=pd.read_csv(r'E:\test\process_lpb\feature_train_full.csv',header=None)
labels = pd.read_csv(r'E:\test\process_lpb\CNO_full.txt',header=None)

'''
# # GIST特征值
subfeatures=pd.read_csv(r'E:\test\process_gist\gist_f_train_full.csv',header=None)
labels = pd.read_csv(r'E:\test\process_gist\CNO_full.txt',header=None)
'''
# # text段代码提取二进制代码，生成图像的LBP特征
# subfeatures=pd.read_csv('/home/stack/Data/Output/lbp_only_text/feature_train_full.csv',header=None)
# labels = pd.read_csv('/home/stack/Data/Output/lbp_only_text/CNO_full.txt',header=None)

# text段 GIST特征
##subfeatures=pd.read_csv(r'E:\test\process_gist\gist_f_train_full.csv',header=None)
##labels = pd.read_csv(r'E:\test\process_gist\CNO_full.txt',header=None)


"\n# # GIST特征值\nsubfeatures=pd.read_csv(r'E:\test\\process_gist\\gist_f_train_full.csv',header=None)\nlabels = pd.read_csv(r'E:\test\\process_gist\\CNO_full.txt',header=None)\n"

In [31]:
"""
# 对全0行进行清除
result = pd.concat([subfeatures, labels], axis=1,ignore_index=True)
'''
print(result)
print(result.apply(lambda x: x.sum(), axis=1))
print(labels.apply(lambda x: x.sum(), axis=1))
print(labels.apply(lambda x: x.sum(), axis=1)==result.apply(lambda x: x.sum(), axis=1))
'''
list=[]
Q = result.apply(lambda x: x.sum(), axis=1)
W = labels.apply(lambda x: x.sum(), axis=1)
for t in range(len(result)):
    if Q[t]==W[t]:
        list.append(t)
print(list,len(list))  #打印出全零行的标号和个数
result=result.drop(labels=list,axis=0)

subfeatures=result.iloc[:,:-1]
labels=result.iloc[:,-1]
"""

"\n# 对全0行进行清除\nresult = pd.concat([subfeatures, labels], axis=1,ignore_index=True)\n'''\nprint(result)\nprint(result.apply(lambda x: x.sum(), axis=1))\nprint(labels.apply(lambda x: x.sum(), axis=1))\nprint(labels.apply(lambda x: x.sum(), axis=1)==result.apply(lambda x: x.sum(), axis=1))\n'''\nlist=[]\nQ = result.apply(lambda x: x.sum(), axis=1)\nW = labels.apply(lambda x: x.sum(), axis=1)\nfor t in range(len(result)):\n    if Q[t]==W[t]:\n        list.append(t)\nprint(list,len(list))  #打印出全零行的标号和个数\nresult=result.drop(labels=list,axis=0)\n\nsubfeatures=result.iloc[:,:-1]\nlabels=result.iloc[:,-1]\n"

In [32]:
#subfeatures.fillna('0')


# 平均准确率归零
avgscore = 0
recallscore = 0
precisionscore = 0
N = 10




In [33]:
# 进行十次KNN测试
for i in range(N):
    # 以10%的比例进行交叉验证
    # X_train, X_test, y_train, y_test = cross_validation.train_test_split(subfeatures, features_labels, test_size=0.1)
    X_train, X_test, y_train, y_test = train_test_split(subfeatures, labels, test_size=0.1)

    # 进行训练
    print('train...')
    # 进行KNN训练,距离为1
    neigh = KNeighborsClassifier(n_neighbors=1)
    neigh.fit(X_train, y_train)

    # 预试
    print('test...')
    c_test = neigh.predict(X_test)

    # print(y_test)
    # print(c_test)

    # 计算预测划分准确率
    print('accurary...')
    score = neigh.score(X_test, y_test)
    print(classification_report(y_test,c_test))
    avgscore = avgscore + score
    recallscore = recallscore + recall_score(y_test,c_test,average="macro")
    precisionscore = precisionscore + precision_score(y_test,c_test,average="macro")
    print(score)

    # 通过混淆矩阵进行结果标示
    cm = confusion_matrix(y_test, c_test)
    np.set_printoptions(threshold=10000)
    np.set_printoptions(precision=2)
    print('Confusion matrix, without normalization\n')
    print(str(cm))

train...


E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.75      0.61      0.67       146
           2       0.98      0.85      0.91       167
           3       0.85      0.81      0.83       108
           4       0.98      1.00      0.99       152
           5       0.99      0.99      0.99       149
           6       0.99      1.00      0.99       144
           7       0.95      0.89      0.92       159
           8       0.67      1.00      0.80       138
           9       0.94      0.89      0.91       161
          10       0.93      0.94      0.94       133

   micro avg       0.90      0.90      0.90      1457
   macro avg       0.90      0.90      0.90      1457
weighted avg       0.91      0.90      0.90      1457

0.8997940974605353
Confusion matrix, without normalization

[[ 89   3   8   0   0   0   4  36   3   3]
 [  8 142   2   0   0   0   0  15   0   0]
 [  4   0  88   0   0   0   3   7   5   1]
 [  0   0   0 152   0   0   0   

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.78      0.54      0.64       155
           2       0.90      0.85      0.87       144
           3       0.81      0.72      0.76       120
           4       1.00      0.99      1.00       145
           5       0.99      0.99      0.99       139
           6       1.00      0.99      1.00       150
           7       0.91      0.91      0.91       148
           8       0.67      1.00      0.80       154
           9       0.95      0.93      0.94       157
          10       0.91      0.92      0.92       145

   micro avg       0.89      0.89      0.89      1457
   macro avg       0.89      0.88      0.88      1457
weighted avg       0.89      0.89      0.88      1457

0.8853809196980096
Confusion matrix, without normalization

[[ 83  11   6   0   1   0   6  37   4   7]
 [  1 122   4   0   0   0   0  17   0   0]
 [  9   1  86   0   0   0   5  12   4   3]
 [  1   0   0 144   0   0   0   

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.79      0.64      0.71       141
           2       0.96      0.88      0.92       171
           3       0.80      0.71      0.76       104
           4       0.97      0.98      0.98       129
           5       0.99      0.99      0.99       161
           6       0.99      0.99      0.99       145
           7       0.90      0.91      0.90       153
           8       0.76      1.00      0.86       167
           9       0.94      0.91      0.93       151
          10       0.93      0.95      0.94       135

   micro avg       0.90      0.90      0.90      1457
   macro avg       0.90      0.90      0.90      1457
weighted avg       0.91      0.90      0.90      1457

0.9032258064516129
Confusion matrix, without normalization

[[ 90   6   6   0   1   0   6  25   4   3]
 [  5 151   0   0   0   0   2  12   1   0]
 [ 10   0  74   0   0   1   5  12   2   0]
 [  1   0   0 127   0   0   0   

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.84      0.63      0.72       162
           2       0.91      0.80      0.85       139
           3       0.85      0.79      0.82       133
           4       0.98      1.00      0.99       167
           5       0.98      0.99      0.98       139
           6       0.98      0.98      0.98       126
           7       0.94      0.92      0.93       145
           8       0.70      1.00      0.83       158
           9       0.93      0.91      0.92       150
          10       0.93      0.96      0.95       138

   micro avg       0.90      0.90      0.90      1457
   macro avg       0.91      0.90      0.90      1457
weighted avg       0.90      0.90      0.89      1457

0.8956760466712422
Confusion matrix, without normalization

[[102   8   9   0   0   0   3  31   4   5]
 [  4 111   2   0   0   0   2  19   0   1]
 [ 10   1 105   0   1   1   1  12   2   0]
 [  0   0   0 167   0   0   0   

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.88      0.66      0.75       160
           2       0.96      0.85      0.90       162
           3       0.85      0.78      0.82        93
           4       0.97      1.00      0.99       148
           5       0.99      1.00      0.99       132
           6       0.98      0.99      0.99       151
           7       0.97      0.92      0.95       158
           8       0.68      1.00      0.81       147
           9       0.94      0.88      0.91       160
          10       0.91      0.95      0.93       146

   micro avg       0.90      0.90      0.90      1457
   macro avg       0.91      0.90      0.90      1457
weighted avg       0.92      0.90      0.90      1457

0.9045984900480439
Confusion matrix, without normalization

[[105   3   5   0   1   1   0  33   3   9]
 [  4 138   3   0   0   0   0  17   0   0]
 [  3   0  73   0   0   0   1  11   4   1]
 [  0   0   0 148   0   0   0   

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.48      0.81      0.60       137
           2       0.96      0.85      0.90       154
           3       0.84      0.77      0.80       120
           4       0.99      0.99      0.99       146
           5       0.99      0.99      0.99       140
           6       1.00      1.00      1.00       154
           7       0.94      0.92      0.93       165
           8       0.98      0.49      0.66       126
           9       0.93      0.88      0.90       165
          10       0.92      0.96      0.94       150

   micro avg       0.88      0.88      0.88      1457
   macro avg       0.90      0.87      0.87      1457
weighted avg       0.91      0.88      0.88      1457

0.8750857927247769
Confusion matrix, without normalization

[[111   3   9   0   1   0   4   1   4   4]
 [ 18 131   3   0   0   0   1   0   0   1]
 [ 18   2  92   0   0   0   3   0   4   1]
 [  0   0   0 145   0   0   1   

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.78      0.65      0.71       161
           2       0.92      0.86      0.89       138
           3       0.38      0.82      0.52       114
           4       0.99      1.00      1.00       134
           5       0.99      0.99      0.99       169
           6       1.00      0.99      0.99       146
           7       0.94      0.92      0.93       139
           8       0.94      0.46      0.62       166
           9       0.95      0.88      0.91       148
          10       0.92      0.94      0.93       142

   micro avg       0.84      0.84      0.84      1457
   macro avg       0.88      0.85      0.85      1457
weighted avg       0.89      0.84      0.85      1457

0.8428277282086479
Confusion matrix, without normalization

[[104   6  40   0   1   0   4   2   1   3]
 [  6 118  13   0   0   0   0   1   0   0]
 [ 12   1  93   0   0   0   1   2   1   4]
 [  0   0   0 134   0   0   0   

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.49      0.85      0.62       144
           2       0.95      0.84      0.89       148
           3       0.90      0.77      0.83       127
           4       0.98      1.00      0.99       136
           5       0.99      1.00      1.00       157
           6       0.99      0.99      0.99       146
           7       0.94      0.90      0.92       150
           8       0.94      0.50      0.66       153
           9       0.94      0.94      0.94       153
          10       0.96      0.95      0.95       143

   micro avg       0.88      0.88      0.88      1457
   macro avg       0.91      0.88      0.88      1457
weighted avg       0.91      0.88      0.88      1457

0.8750857927247769
Confusion matrix, without normalization

[[123   5   7   0   0   0   1   2   3   3]
 [ 19 124   1   0   0   0   2   1   0   1]
 [ 18   1  98   0   0   0   2   2   4   2]
 [  0   0   0 136   0   0   0   

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.91      0.66      0.76       151
           2       0.94      0.88      0.91       149
           3       0.90      0.81      0.85       129
           4       0.99      1.00      1.00       130
           5       1.00      1.00      1.00       136
           6       0.99      1.00      1.00       154
           7       0.90      0.95      0.92       152
           8       0.74      1.00      0.85       151
           9       0.93      0.90      0.91       159
          10       0.89      0.92      0.91       146

   micro avg       0.91      0.91      0.91      1457
   macro avg       0.92      0.91      0.91      1457
weighted avg       0.92      0.91      0.91      1457

0.911461908030199
Confusion matrix, without normalization

[[ 99   5   7   0   0   0   4  23   6   7]
 [  0 131   4   0   0   0   1  12   1   0]
 [  2   3 105   0   0   1   8   8   0   2]
 [  0   0   0 130   0   0   0   0

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.47      0.83      0.60       151
           2       0.96      0.78      0.86       160
           3       0.86      0.72      0.78       109
           4       0.99      0.99      0.99       136
           5       0.99      1.00      1.00       155
           6       0.99      0.98      0.99       138
           7       0.91      0.92      0.91       145
           8       0.97      0.51      0.66       166
           9       0.94      0.95      0.95       137
          10       0.91      0.96      0.93       160

   micro avg       0.86      0.86      0.86      1457
   macro avg       0.90      0.86      0.87      1457
weighted avg       0.90      0.86      0.86      1457

0.8599862731640356
Confusion matrix, without normalization

[[125   3   6   1   1   0   7   0   2   6]
 [ 32 124   2   0   0   0   0   1   0   1]
 [ 17   1  78   0   0   0   5   1   3   4]
 [  0   0   0 135   0   0   1   

In [34]:
# 输出N次的平均准确率
avgscore = avgscore / N
recallscore = recallscore / N
precisionscore = precisionscore / N

print('avgscore....')
print(avgscore)
print('False positive rate')
print(1-precisionscore)
print('false negative rate')
print(1-recallscore)

avgscore....
0.885312285518188
False positive rate
0.09752798198723078
false negative rate
0.11553190395691859
