In [13]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, recall_score, precision_score
from collections import Counter
import pandas as pd
import numpy as np
''' Summary of the file.

    功能：
        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以KNN方法划分并获得准确率，通过混淆矩阵标示结果。

    输出：
        结果的混淆矩阵，每次划分的准确率，十次的平均准确率
'''



' Summary of the file.\n\n    功能：\n        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以KNN方法划分并获得准确率，通过混淆矩阵标示结果。\n\n    输出：\n        结果的混淆矩阵，每次划分的准确率，十次的平均准确率\n'

In [14]:
# 实验室的15000条恶意样本，分为十个家族
# LBP_block
subfeatures=pd.read_csv(r'E:\test\process_lpb_block2\lbp_kmeans_hist_feature.csv',header=None)
labels = pd.read_csv(r'E:\test\process_lpb_block2\ClassNo_full.txt',header=None)

In [15]:
# 把先提取的家族10的特征挪到最后
result = pd.concat([subfeatures, labels], axis=1,ignore_index=True)
# print(result)
result2 = result.iloc[:1431]
list = []
for i in range(len(result)):
    if result.iloc[i,-1] == 10:
        list.append(i)
result = result.drop(list)
result = pd.concat([result,result2],axis=0,ignore_index=True)
subfeatures=result.iloc[:,:-1]
labels=result.iloc[:,-1]

In [16]:
# 平均准确率归零
avgscore = 0
recallscore = 0
precisionscore = 0
N = 10




In [17]:
# 进行十次KNN测试
for i in range(N):
    # 以10%的比例进行交叉验证
    # X_train, X_test, y_train, y_test = cross_validation.train_test_split(subfeatures, features_labels, test_size=0.1)
    X_train, X_test, y_train, y_test = train_test_split(subfeatures, labels, test_size=0.1)

    # 进行训练
    print('train...')
    # 进行KNN训练,距离为1
    neigh = KNeighborsClassifier(n_neighbors=1)
    neigh.fit(X_train, y_train)

    # 预试
    print('test...')
    c_test = neigh.predict(X_test)

    # print(y_test)
    # print(c_test)

    # 计算预测划分准确率
    print('accurary...')
    score = neigh.score(X_test, y_test)
    print(classification_report(y_test,c_test))
    avgscore = avgscore + score
    recallscore = recallscore + recall_score(y_test,c_test,average="macro")
    precisionscore = precisionscore + precision_score(y_test,c_test,average="macro")
    print(score)

    # 通过混淆矩阵进行结果标示
    cm = confusion_matrix(y_test, c_test)
    np.set_printoptions(threshold=10000)
    np.set_printoptions(precision=2)
    print('Confusion matrix, without normalization\n')
    print(str(cm))


train...
test...
accurary...
              precision    recall  f1-score   support

           1       0.66      0.66      0.66       115
           2       0.91      0.93      0.92       147
           3       0.82      0.77      0.79       111
           4       0.94      0.85      0.89       154
           5       0.99      0.97      0.98       159
           6       0.99      0.99      0.99       146
           7       0.89      0.86      0.87       145
           8       0.96      0.99      0.97        79
           9       0.75      0.85      0.80       143
          10       0.89      0.94      0.91       116

   micro avg       0.88      0.88      0.88      1315
   macro avg       0.88      0.88      0.88      1315
weighted avg       0.89      0.88      0.88      1315

0.8828897338403042
Confusion matrix, without normalization

[[ 76   8   6   1   0   0   4   2   9   9]
 [  6 136   4   0   0   0   0   0   0   1]
 [ 10   1  85   1   1   1   7   1   2   2]
 [  5   0   3 131   0  

test...
accurary...
              precision    recall  f1-score   support

           1       0.65      0.67      0.66       128
           2       0.89      0.89      0.89       123
           3       0.76      0.79      0.77       131
           4       0.97      0.82      0.89       139
           5       0.96      1.00      0.98       135
           6       1.00      0.98      0.99       130
           7       0.87      0.93      0.89       147
           8       0.93      0.99      0.96        71
           9       0.78      0.76      0.77       157
          10       0.93      0.93      0.93       154

   micro avg       0.87      0.87      0.87      1315
   macro avg       0.87      0.87      0.87      1315
weighted avg       0.87      0.87      0.87      1315

0.8692015209125475
Confusion matrix, without normalization

[[ 86   1  15   1   1   0   6   3   8   7]
 [  6 109   6   0   0   0   2   0   0   0]
 [  9   7 103   0   2   0   1   2   4   3]
 [  3   1   2 114   0   0   0   

In [18]:
# 输出N次的平均准确率
avgscore = avgscore / N
recallscore = recallscore / N
precisionscore = precisionscore / N

print('avgscore....')
print(avgscore)
print('False positive rate')
print(1-precisionscore)
print('false negative rate')
print(1-recallscore)

avgscore....
0.8668441064638783
False positive rate
0.13177764759509603
false negative rate
0.13229508714185878
