In [14]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, recall_score, precision_score
from collections import Counter
import pandas as pd
import numpy as np
''' Summary of the file.

    功能：
        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以KNN方法划分并获得准确率，通过混淆矩阵标示结果。

    输出：
        结果的混淆矩阵，每次划分的准确率，十次的平均准确率
'''



' Summary of the file.\n\n    功能：\n        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以KNN方法划分并获得准确率，通过混淆矩阵标示结果。\n\n    输出：\n        结果的混淆矩阵，每次划分的准确率，十次的平均准确率\n'

In [15]:
# 实验室的15000条恶意样本，分为十个家族

# # GIST特征值
subfeatures = pd.read_csv(r'E:\test\process_gist2\gist_f_train_full.csv',header=None)
labels = pd.read_csv(r'E:\test\process_gist2\CNO_full.txt',header=None)

# # text段代码提取二进制代码，生成图像的LBP特征
# subfeatures=pd.read_csv('/home/stack/Data/Output/lbp_only_text/feature_train_full.csv',header=None)
# labels = pd.read_csv('/home/stack/Data/Output/lbp_only_text/CNO_full.txt',header=None)

# text段 GIST特征
# #subfeatures=pd.read_csv(r'E:\test\process_gist\gist_f_train_full.csv',header=None)
# #labels = pd.read_csv(r'E:\test\process_gist\CNO_full.txt',header=None)


In [16]:
# 对全NaN列行进行清除
result = pd.concat([subfeatures, labels], axis=1,ignore_index=True)
# print(result)
result=result.dropna(how='all',axis=1)
result=result.dropna(how='any',axis=0)
result=result.reindex()
# print(result)
subfeatures=result.iloc[:,:-1]
labels=result.iloc[:,-1]
print(subfeatures,'\n',labels)

           3         7        11       15        19        23        27   \
1      0.23956  0.237630  0.26381  0.35730  0.084427  0.080236  0.092387   
3      0.18744  0.440850  0.18135  0.35175  0.063265  0.151440  0.060828   
5      0.31370  0.401330  0.28956  0.36062  0.108090  0.140850  0.100460   
7      0.33926  0.308770  0.34102  0.23674  0.116410  0.107190  0.115250   
8      0.32031  0.239320  0.23991  0.34135  0.112280  0.082963  0.081881   
9      0.16760  0.245140  0.10508  0.26727  0.059215  0.082231  0.034979   
10     0.25577  0.327910  0.34899  0.30896  0.086576  0.113710  0.120750   
11     0.40402  0.350880  0.28529  0.27655  0.139750  0.120110  0.097166   
12     0.26433  0.293290  0.26679  0.28659  0.087935  0.101590  0.090306   
13     0.40280  0.359690  0.36875  0.41921  0.138480  0.126010  0.128750   
14     0.27751  0.079934  0.24908  0.10085  0.094805  0.028159  0.085137   
15     0.31480  0.232990  0.29155  0.27720  0.110780  0.080156  0.101760   
17     0.325

In [17]:
# 平均准确率归零
avgscore = 0
recallscore = 0
precisionscore = 0
N = 10

# 进行十次KNN测试
for i in range(N):
    # 以10%的比例进行交叉验证
    #X_train, X_test, y_train, y_test = cross_validation.train_test_split(subfeatures, features_labels, test_size=0.1)
    X_train, X_test, y_train, y_test = train_test_split(subfeatures, labels, test_size=0.1)

    # 进行训练
    print('train...')
    # 进行KNN训练,距离为1
    neigh = KNeighborsClassifier(n_neighbors=1)
    neigh.fit(X_train, y_train)

    # 预试
    print('test...')
    c_test = neigh.predict(X_test)

    # print(y_test)
    # print(c_test)

    # 计算预测划分准确率
    print('accurary...')
    score = neigh.score(X_test, y_test)
    print(classification_report(y_test,c_test))
    avgscore = avgscore + score
    recallscore = recallscore + recall_score(y_test,c_test,average="macro")
    precisionscore = precisionscore + precision_score(y_test,c_test,average="macro")
    print(score)

    # 通过混淆矩阵进行结果标示
    cm = confusion_matrix(y_test, c_test)
    np.set_printoptions(threshold=10000)
    np.set_printoptions(precision=2)
    print('Confusion matrix, without normalization')
    print(str(cm))


train...
test...
accurary...
              precision    recall  f1-score   support

           1       0.51      0.50      0.50       132
           2       0.82      0.83      0.83       130
           3       0.67      0.70      0.69       103
           4       0.47      0.46      0.47       141
           5       0.98      0.99      0.99       142
           6       0.99      0.99      0.99        67
           7       0.87      0.87      0.87       150
           8       0.94      0.96      0.95        78
           9       0.82      0.81      0.81       156
          10       0.81      0.80      0.81       140

   micro avg       0.78      0.78      0.78      1239
   macro avg       0.79      0.79      0.79      1239
weighted avg       0.78      0.78      0.78      1239

0.7764326069410815
Confusion matrix, without normalization
[[ 66   6  10  22   0   1   5   2   6  14]
 [  3 108   4   9   0   0   1   1   2   2]
 [  7   1  72  13   1   0   2   0   5   2]
 [ 25  10  13  65   1   

accurary...
              precision    recall  f1-score   support

           1       0.56      0.49      0.52       118
           2       0.79      0.91      0.85       118
           3       0.73      0.76      0.75       100
           4       0.56      0.54      0.55       158
           5       0.98      1.00      0.99       142
           6       0.99      0.98      0.98        87
           7       0.86      0.75      0.80       142
           8       0.89      0.95      0.92        83
           9       0.76      0.80      0.78       157
          10       0.81      0.82      0.81       134

   micro avg       0.79      0.79      0.79      1239
   macro avg       0.79      0.80      0.80      1239
weighted avg       0.78      0.79      0.78      1239

0.7861178369652946
Confusion matrix, without normalization
[[ 58   4   6  24   0   0   7   2   7  10]
 [  0 107   2   6   0   0   0   1   0   2]
 [  6   1  76  12   0   0   0   1   3   1]
 [ 18  11  12  85   2   0   5   4  12   9

In [18]:
# 输出N次的平均准确率
avgscore = avgscore / N
recallscore = recallscore / N
precisionscore = precisionscore / N

print('avgscore....')
print(avgscore)
print('False positive rate')
print(1-precisionscore)
print('false negative rate')
print(1-recallscore)


avgscore....
0.7800645682001615
False positive rate
0.20943242023385056
false negative rate
0.2083126031032564
