In [13]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, recall_score, precision_score
from collections import Counter
import pandas as pd
import numpy as np
''' Summary of the file.

    功能：
        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以KNN方法划分并获得准确率，通过混淆矩阵标示结果。

    输出：
        结果的混淆矩阵，每次划分的准确率，十次的平均准确率
'''



' Summary of the file.\n\n    功能：\n        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以KNN方法划分并获得准确率，通过混淆矩阵标示结果。\n\n    输出：\n        结果的混淆矩阵，每次划分的准确率，十次的平均准确率\n'

In [14]:
# 实验室的15000条恶意样本，分为十个家族
# # LBP特征值
subfeatures=pd.read_csv(r'F:\virtus_test\Simhash_LBPv2\feature_train_full.csv',header=None)
labels = pd.read_csv(r'F:\virtus_test\Simhash_LBPv2\CNO_full.txt',header=None)

'''
# # GIST特征值
subfeatures=pd.read_csv(r'E:\test\process_gist\gist_f_train_full.csv',header=None)
labels = pd.read_csv(r'E:\test\process_gist\CNO_full.txt',header=None)
'''
# # text段代码提取二进制代码，生成图像的LBP特征
# subfeatures=pd.read_csv('/home/stack/Data/Output/lbp_only_text/feature_train_full.csv',header=None)
# labels = pd.read_csv('/home/stack/Data/Output/lbp_only_text/CNO_full.txt',header=None)

# text段 GIST特征
##subfeatures=pd.read_csv(r'E:\test\process_gist\gist_f_train_full.csv',header=None)
##labels = pd.read_csv(r'E:\test\process_gist\CNO_full.txt',header=None)


"\n# # GIST特征值\nsubfeatures=pd.read_csv(r'E:\test\\process_gist\\gist_f_train_full.csv',header=None)\nlabels = pd.read_csv(r'E:\test\\process_gist\\CNO_full.txt',header=None)\n"

In [15]:
# # 删除数据量较小的数据
# result = pd.concat([subfeatures, labels], axis=1,ignore_index=True)
# '''
# print(result)
# print(result.apply(lambda x: x.sum(), axis=1))
# print(labels.apply(lambda x: x.sum(), axis=1))
# print(labels.apply(lambda x: x.sum(), axis=1)==result.apply(lambda x: x.sum(), axis=1))
# '''
# list=[]
# Q = result.apply(lambda x: x.sum(), axis=1)
# # W = labels.apply(lambda x: x.sum(), axis=1)
# for t in range(len(result)):
#     if Q[t] <= 2.5:
#         list.append(t)
# # print(list,len(list))  #打印出较小数据量的标号和个数
# result=result.drop(labels=list,axis=0)

# subfeatures=result.iloc[:,:-1]
# labels=result.iloc[:,-1]
# print (subfeatures)

In [16]:
#subfeatures.fillna('0')


# 平均准确率归零
avgscore = 0
recallscore = 0
precisionscore = 0
N = 10




In [17]:
# 进行十次KNN测试
for i in range(N):
    # 以10%的比例进行交叉验证
    # X_train, X_test, y_train, y_test = cross_validation.train_test_split(subfeatures, features_labels, test_size=0.1)
    X_train, X_test, y_train, y_test = train_test_split(subfeatures, labels, test_size=0.1)

    # 进行训练
    print('train...')
    # 进行KNN训练,距离为1
    neigh = KNeighborsClassifier(n_neighbors=1)
    neigh.fit(X_train, y_train)

    # 预试
    print('test...')
    c_test = neigh.predict(X_test)

    # print(y_test)
    # print(c_test)

    # 计算预测划分准确率
    print('accurary...')
    score = neigh.score(X_test, y_test)
    print(classification_report(y_test,c_test))
    avgscore = avgscore + score
    recallscore = recallscore + recall_score(y_test,c_test,average="macro")
    precisionscore = precisionscore + precision_score(y_test,c_test,average="macro")
    print(score)

    # 通过混淆矩阵进行结果标示
    cm = confusion_matrix(y_test, c_test)
    np.set_printoptions(threshold=10000)
    np.set_printoptions(precision=2)
    print('Confusion matrix, without normalization\n')
    print(str(cm))

train...


E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.59      0.30      0.40       137
           2       0.86      0.73      0.79       165
           3       0.88      0.54      0.67       147
           4       0.99      0.95      0.97       139
           5       0.99      0.92      0.95       164
           6       0.90      1.00      0.94       146
           7       0.94      0.92      0.93       161
           8       0.48      1.00      0.65       162
           9       0.91      0.88      0.90       138
          10       0.90      0.74      0.81       116

   micro avg       0.81      0.81      0.81      1475
   macro avg       0.84      0.80      0.80      1475
weighted avg       0.84      0.81      0.80      1475

0.8054237288135593
Confusion matrix, without normalization

[[ 41   9   3   2   0   3   0  69   2   8]
 [  6 121   2   0   0   0   4  27   5   0]
 [ 12   6  79   0   0   3   1  44   1   1]
 [  1   0   0 132   0   0   0   

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.66      0.28      0.40       130
           2       0.92      0.87      0.89       132
           3       0.86      0.52      0.65       151
           4       0.99      0.97      0.98       150
           5       0.93      0.91      0.92       160
           6       0.90      0.93      0.91       162
           7       0.33      0.91      0.48       151
           8       0.96      0.34      0.50       160
           9       0.89      0.88      0.89       144
          10       0.92      0.80      0.85       135

   micro avg       0.74      0.74      0.74      1475
   macro avg       0.84      0.74      0.75      1475
weighted avg       0.84      0.74      0.75      1475

0.744406779661017
Confusion matrix, without normalization

[[ 37   3   4   0   0   1  75   0   3   7]
 [  2 115   1   0   0   0  12   1   1   0]
 [  6   2  79   0   0   1  59   0   3   1]
 [  3   0   0 145   0   0   2   0

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.34      0.81      0.48       145
           2       0.83      0.76      0.80       130
           3       0.79      0.47      0.59       134
           4       0.99      0.91      0.95       164
           5       0.97      0.90      0.94       154
           6       0.90      0.98      0.93       166
           7       0.90      0.95      0.92       142
           8       0.93      0.29      0.44       146
           9       0.90      0.75      0.82       150
          10       0.81      0.76      0.78       144

   micro avg       0.76      0.76      0.76      1475
   macro avg       0.84      0.76      0.76      1475
weighted avg       0.84      0.76      0.77      1475

0.7647457627118645
Confusion matrix, without normalization

[[117   6   5   2   1   1   3   2   3   5]
 [ 27  99   0   0   0   0   0   0   4   0]
 [ 52   2  63   0   1   4   3   1   4   4]
 [  1   0   0 149   0   0   0   

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.34      0.86      0.49       142
           2       0.90      0.82      0.86       154
           3       0.84      0.53      0.65       152
           4       1.00      1.00      1.00       136
           5       0.99      0.90      0.94       148
           6       0.90      0.97      0.93       157
           7       0.93      0.85      0.89       162
           8       0.98      0.29      0.45       148
           9       0.81      0.85      0.83       133
          10       0.95      0.73      0.82       143

   micro avg       0.78      0.78      0.78      1475
   macro avg       0.86      0.78      0.79      1475
weighted avg       0.86      0.78      0.79      1475

0.7783050847457628
Confusion matrix, without normalization

[[122   6   4   0   0   1   0   1   5   3]
 [ 21 126   4   0   0   0   2   0   1   0]
 [ 64   2  81   0   0   2   1   0   2   0]
 [  0   0   0 136   0   0   0   

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.71      0.31      0.43       163
           2       0.82      0.79      0.80       154
           3       0.77      0.50      0.61       148
           4       0.98      0.95      0.97       153
           5       0.97      0.85      0.90       140
           6       0.86      0.97      0.91       146
           7       0.93      0.91      0.92       151
           8       0.43      0.95      0.59       152
           9       0.92      0.83      0.87       128
          10       0.93      0.82      0.87       140

   micro avg       0.78      0.78      0.78      1475
   macro avg       0.83      0.79      0.79      1475
weighted avg       0.83      0.78      0.78      1475

0.7823728813559322
Confusion matrix, without normalization

[[ 50   7   9   3   0   1   5  80   2   6]
 [  3 121   3   0   0   0   0  22   5   0]
 [  2   7  74   0   0   4   2  56   0   3]
 [  0   0   0 146   0   0   0   

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.64      0.37      0.47       154
           2       0.92      0.79      0.85       151
           3       0.81      0.50      0.61       143
           4       1.00      0.98      0.99       124
           5       0.99      0.89      0.94       157
           6       0.88      0.99      0.93       156
           7       0.88      0.76      0.82       139
           8       0.94      0.32      0.47       145
           9       0.78      0.83      0.81       148
          10       0.35      0.89      0.50       158

   micro avg       0.73      0.73      0.73      1475
   macro avg       0.82      0.73      0.74      1475
weighted avg       0.81      0.73      0.74      1475

0.7308474576271187
Confusion matrix, without normalization

[[ 57   3   3   0   1   0   2   1   5  82]
 [  3 120   3   0   0   0   3   0   3  19]
 [  7   3  71   0   0   3   4   2   4  49]
 [  0   0   0 121   0   0   0   

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.36      0.82      0.50       161
           2       0.89      0.78      0.83       135
           3       0.85      0.58      0.69       161
           4       0.99      0.93      0.96       158
           5       1.00      0.88      0.94       140
           6       0.86      0.99      0.92       146
           7       0.89      0.88      0.89       151
           8       0.98      0.30      0.46       135
           9       0.88      0.81      0.84       139
          10       0.92      0.79      0.85       149

   micro avg       0.78      0.78      0.78      1475
   macro avg       0.86      0.78      0.79      1475
weighted avg       0.86      0.78      0.79      1475

0.7783050847457628
Confusion matrix, without normalization

[[132   5   7   2   0   2   0   0   5   8]
 [ 22 105   1   0   0   0   3   1   3   0]
 [ 58   1  93   0   0   3   4   0   2   0]
 [ 11   0   0 147   0   0   0   

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.70      0.35      0.47       158
           2       0.91      0.81      0.86       153
           3       0.82      0.58      0.68       150
           4       1.00      0.99      1.00       135
           5       0.99      0.91      0.95       146
           6       0.91      0.98      0.95       150
           7       0.92      0.86      0.88       152
           8       0.51      0.99      0.67       175
           9       0.91      0.90      0.90       124
          10       0.92      0.83      0.87       132

   micro avg       0.82      0.82      0.82      1475
   macro avg       0.86      0.82      0.82      1475
weighted avg       0.85      0.82      0.81      1475

0.8169491525423729
Confusion matrix, without normalization

[[ 56   6   9   0   0   0   1  79   1   6]
 [  4 124   3   0   0   0   0  18   4   0]
 [  2   1  87   0   1   3   3  48   2   3]
 [  0   0   0 134   0   0   0   

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.59      0.24      0.34       161
           2       0.87      0.79      0.83       151
           3       0.80      0.56      0.66       147
           4       0.99      0.99      0.99       148
           5       0.99      0.92      0.95       149
           6       0.90      0.97      0.94       136
           7       0.89      0.91      0.90       164
           8       0.45      1.00      0.62       147
           9       0.88      0.80      0.84       134
          10       0.90      0.82      0.86       138

   micro avg       0.79      0.79      0.79      1475
   macro avg       0.83      0.80      0.79      1475
weighted avg       0.83      0.79      0.79      1475

0.7945762711864407
Confusion matrix, without normalization

[[ 38   5  11   2   0   3   5  85   3   9]
 [  8 119   2   0   0   0   0  19   3   0]
 [  6   4  82   0   1   0   4  45   4   1]
 [  0   0   0 147   0   0   0   

E:\Anacondaa\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


test...
accurary...
              precision    recall  f1-score   support

           1       0.63      0.24      0.35       142
           2       0.86      0.87      0.87       126
           3       0.80      0.48      0.60       147
           4       1.00      0.98      0.99       139
           5       0.96      0.91      0.94       151
           6       0.92      0.97      0.94       158
           7       0.90      0.84      0.87       141
           8       0.51      0.99      0.67       175
           9       0.87      0.85      0.86       156
          10       0.88      0.83      0.85       140

   micro avg       0.80      0.80      0.80      1475
   macro avg       0.83      0.80      0.79      1475
weighted avg       0.83      0.80      0.79      1475

0.8013559322033899
Confusion matrix, without normalization

[[ 34   6   7   0   1   1   2  83   0   8]
 [  4 110   1   0   0   0   1   8   2   0]
 [  8   6  70   0   0   3   4  49   3   4]
 [  0   0   0 136   0   0   0   

In [18]:
# 输出N次的平均准确率
avgscore = avgscore / N
recallscore = recallscore / N
precisionscore = precisionscore / N

print('avgscore....')
print(avgscore)
print('False positive rate')
print(1-precisionscore)
print('false negative rate')
print(1-recallscore)

avgscore....
0.7797288135593221
False positive rate
0.15913633070241373
false negative rate
0.2213616546916357
