In [11]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, recall_score, precision_score
from collections import Counter
import pandas as pd
import numpy as np
''' Summary of the file.

    功能：
        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以KNN方法划分并获得准确率，通过混淆矩阵标示结果。

    输出：
        结果的混淆矩阵，每次划分的准确率，十次的平均准确率
'''



' Summary of the file.\n\n    功能：\n        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以KNN方法划分并获得准确率，通过混淆矩阵标示结果。\n\n    输出：\n        结果的混淆矩阵，每次划分的准确率，十次的平均准确率\n'

In [12]:
# 实验室的15000条恶意样本，分为十个家族

# # GIST特征值
subfeatures = pd.read_csv(r'F:\virtus_test\Simhash_Gistv2\gist_f_train_full.csv',header=None)
labels = pd.read_csv(r'F:\virtus_test\Simhash_Gistv2\CNO_full.txt',header=None)

# # text段代码提取二进制代码，生成图像的LBP特征
# subfeatures=pd.read_csv('/home/stack/Data/Output/lbp_only_text/feature_train_full.csv',header=None)
# labels = pd.read_csv('/home/stack/Data/Output/lbp_only_text/CNO_full.txt',header=None)

# text段 GIST特征
# #subfeatures=pd.read_csv(r'E:\test\process_gist\gist_f_train_full.csv',header=None)
# #labels = pd.read_csv(r'E:\test\process_gist\CNO_full.txt',header=None)


In [13]:
# 对全NaN列行进行清除
result = pd.concat([subfeatures, labels], axis=1,ignore_index=True)
# print(result)
result=result.dropna(how='all',axis=1)
result=result.dropna(how='any',axis=0)
result=result.reindex()
# print(result)
subfeatures=result.iloc[:,:-1]
labels=result.iloc[:,-1]
print(subfeatures,'\n',labels)

            0         1         2         3         4         5         6    \
1      0.000025  0.000042  0.001947  0.000118  0.000027  0.000046  0.009525   
3      0.021550  0.007681  0.031629  0.015364  0.017454  0.000460  0.030582   
5      0.001903  0.000339  0.007303  0.000272  0.012126  0.000163  0.012807   
8      0.002287  0.000333  0.014099  0.000369  0.011018  0.000194  0.011269   
9      0.027110  0.006912  0.045522  0.023629  0.020981  0.008361  0.039535   
10     0.037260  0.017591  0.055027  0.036390  0.027287  0.008496  0.043107   
12     0.031269  0.007804  0.040050  0.018106  0.019535  0.000554  0.027900   
14     0.001719  0.000278  0.007214  0.000267  0.005511  0.000162  0.012874   
17     0.000027  0.000042  0.002761  0.000117  0.000028  0.000045  0.011897   
21     0.012974  0.000319  0.007631  0.000222  0.013669  0.000194  0.020849   
23     0.007849  0.000221  0.007033  0.007127  0.012704  0.000163  0.012380   
24     0.012538  0.000630  0.016398  0.000351  0.018

In [14]:
# 平均准确率归零
avgscore = 0
recallscore = 0
precisionscore = 0
N = 10

# 进行十次KNN测试
for i in range(N):
    # 以10%的比例进行交叉验证
    #X_train, X_test, y_train, y_test = cross_validation.train_test_split(subfeatures, features_labels, test_size=0.1)
    X_train, X_test, y_train, y_test = train_test_split(subfeatures, labels, test_size=0.1)

    # 进行训练
    print('train...')
    # 进行KNN训练,距离为1
    neigh = KNeighborsClassifier(n_neighbors=1)
    neigh.fit(X_train, y_train)

    # 预试
    print('test...')
    c_test = neigh.predict(X_test)

    # print(y_test)
    # print(c_test)

    # 计算预测划分准确率
    print('accurary...')
    score = neigh.score(X_test, y_test)
    print(classification_report(y_test,c_test))
    avgscore = avgscore + score
    recallscore = recallscore + recall_score(y_test,c_test,average="macro")
    precisionscore = precisionscore + precision_score(y_test,c_test,average="macro")
    print(score)

    # 通过混淆矩阵进行结果标示
    cm = confusion_matrix(y_test, c_test)
    np.set_printoptions(threshold=10000)
    np.set_printoptions(precision=2)
    print('Confusion matrix, without normalization')
    print(str(cm))


train...
test...
accurary...
              precision    recall  f1-score   support

           1       0.65      0.70      0.67        56
           2       0.93      0.92      0.93       128
           3       0.91      0.82      0.86       100
           4       1.00      1.00      1.00       136
           5       0.99      0.90      0.94       148
           6       0.91      0.99      0.95       171
           7       0.93      0.95      0.94       167
           8       0.96      1.00      0.98        48
           9       0.93      0.87      0.90       119
          10       0.92      0.98      0.95       125

   micro avg       0.93      0.93      0.93      1198
   macro avg       0.91      0.91      0.91      1198
weighted avg       0.93      0.93      0.93      1198

0.9273789649415692
Confusion matrix, without normalization
[[ 39   5   4   0   0   0   1   1   2   4]
 [  7 118   1   0   0   0   1   1   0   0]
 [  7   3  82   0   0   2   1   0   1   4]
 [  0   0   0 136   0   

test...
accurary...
              precision    recall  f1-score   support

           1       0.76      0.55      0.64        77
           2       0.90      0.97      0.93       132
           3       0.44      0.85      0.58        98
           4       1.00      1.00      1.00       154
           5       0.99      0.92      0.96       143
           6       0.95      0.48      0.63       151
           7       0.91      0.91      0.91       144
           8       0.95      1.00      0.97        39
           9       0.92      0.87      0.89       124
          10       0.88      0.95      0.91       136

   micro avg       0.85      0.85      0.85      1198
   macro avg       0.87      0.85      0.84      1198
weighted avg       0.89      0.85      0.85      1198

0.8497495826377296
Confusion matrix, without normalization
[[ 42  10   7   0   1   0   1   1   4  11]
 [  2 128   1   0   0   0   1   0   0   0]
 [  8   0  83   0   0   0   3   0   1   3]
 [  0   0   0 154   0   0   0   0

In [15]:
# 输出N次的平均准确率
avgscore = avgscore / N
recallscore = recallscore / N
precisionscore = precisionscore / N

print('avgscore....')
print(avgscore)
print('False positive rate')
print(1-precisionscore)
print('false negative rate')
print(1-recallscore)


avgscore....
0.901752921535893
False positive rate
0.10132662404481363
false negative rate
0.10647692406175602
