In [7]:
from sklearn.ensemble import RandomForestClassifier as RF
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,precision_score,recall_score
from collections import Counter
import pandas as pd
import numpy as np

''' Summary of the file.
    
    功能：
        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以随机森林方法划分并获得准确率，通过混淆矩阵标示结果。
    
    输出：
        结果的混淆矩阵，每次划分的准确率，十次的平均准确率
'''



' Summary of the file.\n    \n    功能：\n        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以随机森林方法划分并获得准确率，通过混淆矩阵标示结果。\n    \n    输出：\n        结果的混淆矩阵，每次划分的准确率，十次的平均准确率\n'

In [8]:
# # LBP特征值
subfeatures = pd.read_csv(r'F:\virtus_test\Simhash_Gist\gist_f_train_full.csv',header=None)
labels = pd.read_csv(r'F:\virtus_test\Simhash_Gist\CNO_full.txt',header=None)

In [9]:
# 对全0行进行清除
result = pd.concat([subfeatures, labels], axis=1,ignore_index=True)
'''
print(result)
print(result.apply(lambda x: x.sum(), axis=1))
print(labels.apply(lambda x: x.sum(), axis=1))
print(labels.apply(lambda x: x.sum(), axis=1)==result.apply(lambda x: x.sum(), axis=1))
'''
list=[]
Q = result.apply(lambda x: x.sum(), axis=1)
W = labels.apply(lambda x: x.sum(), axis=1)
for t in range(len(result)):
    if Q[t]==W[t]:
        list.append(t)
print(list,len(list))  #打印出全零行的标号和个数
result=result.drop(labels=list,axis=0)

subfeatures=result.iloc[:,:-1]
labels=result.iloc[:,-1]

[0, 2, 4, 6, 7, 11, 13, 15, 16, 18, 19, 20, 22, 25, 26, 29, 30, 31, 32, 33, 34, 37, 38, 39, 40, 41, 45, 46, 47, 51, 52, 54, 59, 60, 61, 62, 64, 66, 67, 68, 69, 70, 72, 74, 75, 78, 83, 84, 85, 87, 88, 91, 92, 93, 94, 96, 98, 99, 102, 103, 104, 106, 108, 109, 112, 114, 116, 118, 119, 120, 122, 123, 124, 126, 127, 128, 132, 133, 134, 135, 137, 140, 141, 143, 145, 146, 147, 148, 153, 154, 156, 158, 159, 160, 161, 162, 163, 164, 165, 166, 169, 170, 171, 173, 175, 181, 182, 183, 184, 187, 188, 189, 193, 195, 196, 197, 198, 199, 202, 204, 205, 206, 207, 209, 211, 216, 218, 220, 223, 224, 226, 229, 230, 231, 233, 237, 238, 242, 243, 244, 246, 247, 253, 255, 256, 257, 259, 260, 261, 262, 263, 265, 267, 269, 270, 272, 276, 277, 279, 280, 281, 282, 283, 284, 287, 288, 289, 293, 295, 297, 298, 299, 302, 303, 305, 307, 312, 315, 316, 319, 321, 322, 323, 324, 325, 329, 331, 333, 336, 340, 343, 345, 349, 351, 352, 353, 354, 356, 357, 358, 359, 360, 362, 364, 365, 368, 375, 376, 377, 378, 379, 380, 38

In [10]:
# 平均准确率归零
avgscore = 0
recallscore = 0
precisionscore = 0
N = 10


In [11]:
# 进行十次随机森林测试
for i in range(N):
    # 以10%的比例进行交叉验证
    # X_train, X_test, y_train, y_test = cross_validation.train_test_split(subfeatures,features_labels,test_size=0.1)
    X_train, X_test, y_train, y_test = train_test_split(subfeatures, labels, test_size=0.1)

    # 进行训练
    print('train...')
    # 进行随机森林训练,30课树，不限制进程数
    srf = RF(n_estimators=30, n_jobs=-1)
    srf.fit(X_train, y_train)

    # 预试
    print("test...")
    c_test = srf.predict(X_test)


    # 计算预测划分准确率
    score = srf.score(X_test, y_test)
    print(score)
    print(classification_report(y_test,c_test))
    # print("c_test")
    # print(c_test)
    # print('y_test')
    # print(y_test)

    avgscore = avgscore + score
    recallscore = recallscore + recall_score(y_test,c_test,average="macro")
    precisionscore = precisionscore + precision_score(y_test,c_test,average="macro")
    print(" initial test  labels size")

    # 通过混淆矩阵进行结果标示
    cm = confusion_matrix(y_test, c_test)
    np.set_printoptions(threshold=10000)
    np.set_printoptions(precision=2)
    print('Confusion matrix, without normalization')
    print(str(cm))



train...
test...
0.9357262103505843
              precision    recall  f1-score   support

           1       0.80      0.73      0.76        71
           2       0.97      0.96      0.96       143
           3       0.83      0.86      0.84        83
           4       0.98      1.00      0.99       150
           5       1.00      0.89      0.94       170
           6       0.88      0.98      0.93       149
           7       0.98      0.95      0.97       162
           8       0.98      0.98      0.98        43
           9       0.90      0.95      0.92       116
          10       0.95      0.97      0.96       111

   micro avg       0.94      0.94      0.94      1198
   macro avg       0.93      0.93      0.93      1198
weighted avg       0.94      0.94      0.94      1198

 initial test  labels size
Confusion matrix, without normalization
[[ 52   3   9   1   0   1   0   0   2   3]
 [  3 137   1   0   0   0   0   1   1   0]
 [  3   0  71   1   0   0   2   0   3   3]
 [  0   0

test...
0.9432387312186978
              precision    recall  f1-score   support

           1       0.75      0.77      0.76        70
           2       0.95      0.95      0.95       125
           3       0.90      0.92      0.91        85
           4       1.00      0.99      1.00       147
           5       1.00      0.91      0.96       151
           6       0.92      1.00      0.96       161
           7       0.96      0.93      0.95       140
           8       0.98      0.98      0.98        45
           9       0.90      0.93      0.92       138
          10       0.99      0.96      0.98       136

   micro avg       0.94      0.94      0.94      1198
   macro avg       0.94      0.94      0.93      1198
weighted avg       0.94      0.94      0.94      1198

 initial test  labels size
Confusion matrix, without normalization
[[ 54   3   5   0   0   0   0   0   7   1]
 [  2 119   1   0   0   0   1   1   1   0]
 [  3   0  78   0   0   0   1   0   3   0]
 [  1   0   0 146 

In [12]:
# 输出N次的平均准确率
avgscore = avgscore / N
recallscore = recallscore / N
precisionscore = precisionscore / N

print('avgscore....')
print(avgscore)
print('False positive rate')
print(1-precisionscore)
print('false negative rate')
print(1-recallscore)


avgscore....
0.9394824707846411
False positive rate
0.06964328342466497
false negative rate
0.07075885635784418
