In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
from sklearn import tree
from sklearn.linear_model import LinearRegression
from scipy import stats
import pylab as pl
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, recall_score, precision_score
import math
from sklearn.datasets.samples_generator import make_blobs
from sklearn.svm import SVC

from pandas import DataFrame
''' Summary of the file.

    功能：
        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以KNN方法划分并获得准确率，通过混淆矩阵标示结果。

    输出：
        结果的混淆矩阵，每次划分的准确率，十次的平均准确率
'''



' Summary of the file.\n\n    功能：\n        读取特征值文件和标签文件，通过交叉验证获得训练集和测试集，以KNN方法划分并获得准确率，通过混淆矩阵标示结果。\n\n    输出：\n        结果的混淆矩阵，每次划分的准确率，十次的平均准确率\n'

In [20]:
# LBP特征值
subfeatures=pd.read_csv(r'E:\test\process_lpb\feature_train_full.csv',header=None)
labels = pd.read_csv(r'E:\test\process_lpb\CNO_full.txt',header=None)



In [21]:
# 对全0行进行清除
result = pd.concat([subfeatures, labels], axis=1,ignore_index=True)
'''
print(result)
print(result.apply(lambda x: x.sum(), axis=1))
print(labels.apply(lambda x: x.sum(), axis=1))
print(labels.apply(lambda x: x.sum(), axis=1)==result.apply(lambda x: x.sum(), axis=1))
'''
list=[]
Q = result.apply(lambda x: x.sum(), axis=1)
W = labels.apply(lambda x: x.sum(), axis=1)
for t in range(len(result)):
    if Q[t]==W[t]:
        list.append(t)
print(list,len(list))  #打印出全零行的标号和个数
result=result.drop(labels=list,axis=0)

subfeatures=result.iloc[:,:-1]
labels=result.iloc[:,-1]

[0, 2, 4, 6, 16, 19, 20, 22, 26, 30, 46, 52, 53, 66, 74, 80, 86, 87, 89, 95, 96, 100, 101, 116, 128, 129, 130, 135, 139, 141, 143, 158, 168, 183, 189, 190, 191, 194, 201, 204, 218, 227, 232, 234, 236, 241, 245, 246, 248, 261, 262, 264, 265, 267, 269, 279, 280, 300, 301, 302, 307, 316, 326, 327, 328, 329, 334, 351, 355, 358, 360, 362, 363, 365, 374, 382, 385, 387, 402, 403, 407, 408, 416, 424, 430, 434, 438, 442, 454, 457, 464, 465, 471, 472, 477, 490, 495, 501, 521, 525, 528, 546, 548, 549, 550, 553, 557, 565, 568, 569, 570, 578, 583, 584, 589, 594, 610, 611, 615, 617, 622, 631, 635, 644, 646, 647, 670, 675, 680, 686, 688, 689, 692, 693, 719, 722, 730, 734, 737, 743, 751, 757, 781, 787, 791, 792, 802, 807, 811, 815, 824, 836, 837, 840, 852, 858, 871, 872, 874, 890, 907, 910, 931, 934, 943, 952, 956, 958, 961, 964, 974, 980, 981, 985, 991, 997, 1003, 1004, 1015, 1021, 1030, 1031, 1033, 1034, 1056, 1064, 1067, 1074, 1092, 1097, 1098, 1108, 1110, 1119, 1133, 1134, 1135, 1136, 1153, 1165, 

In [22]:
'''
if min(set(list(labels.T.ix[0, :]))) == 1:
    labels = labels - 1

classNumber = len(set(list(labels.T.ix[0, :])))
print(classNumber)

subfeatures = pd.DataFrame(subfeatures, dtype=float)

for i in range(len(subfeatures)):
    if math.isnan(float(subfeatures.ix[i, 0])):
        subfeatures.ix[i] = subfeatures.ix[i - 1]


subfeatures = pd.DataFrame(subfeatures, dtype=float)

for i in range(len(subfeatures)):
    if math.isnan(float(subfeatures.ix[i, 0])):
        subfeatures.ix[i] = subfeatures.ix[i - 1]
'''
# 平均准确率归零
avgscore = 0
recallscore = 0
precisionscore = 0
N = 10





In [23]:
# 进行十次SVM_Tree测试
for i in range(N):
    # 以10%的比例进行交叉验证
    # X_train, X_test, y_train, y_test = cross_validation.train_test_split(subfeatures, features_labels, test_size=0.1)
    X_train, X_test, y_train, y_test = train_test_split(subfeatures, labels, test_size=0.1)

    # 进行训练
    print('train...')
    # 进行SVC训练 使用线性核
    clf = SVC(kernel='linear')                     # 高斯核 rbf
    # clf = tree.DecisionTreeClassifier()
    clf.fit(X_train.values, y_train.values.reshape(len(y_train)))

    # 预试
    print('test...')
    c_test = clf.predict(X_test.values)

    # print(y_test)
    # print(c_test)

    # 计算预测划分准确率
    print('accurary...')
    score = clf.score(X_test.values, y_test.values.reshape(len(y_test)))
    print(classification_report(y_test, c_test))
    avgscore = avgscore + score
    recallscore = recallscore + recall_score(y_test, c_test, average="macro")
    precisionscore = precisionscore + precision_score(y_test, c_test, average="macro")
    print(score)

    # 通过混淆矩阵进行结果标示
    cm = confusion_matrix(y_test, c_test)
    np.set_printoptions(threshold=10000)
    np.set_printoptions(precision=2)
    print('Confusion matrix, without normalization')
    print(str(cm))



train...
test...
accurary...


E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           1       0.50      0.01      0.02       113
           2       0.00      0.00      0.00       126
           3       0.00      0.00      0.00       125
           4       0.55      0.96      0.70       158
           5       0.00      0.00      0.00       137
           6       0.90      0.69      0.78       130
           7       0.21      0.81      0.33       171
           8       0.00      0.00      0.00        73
           9       0.29      0.24      0.26       136
          10       0.43      0.37      0.40       152

   micro avg       0.36      0.36      0.36      1321
   macro avg       0.29      0.31      0.25      1321
weighted avg       0.30      0.36      0.28      1321

0.3557910673732021
Confusion matrix, without normalization
[[  1   1   0  15   3   3  61   0  23   6]
 [  0   0   0   0   0   0 126   0   0   0]
 [  1   7   0   8   1   1  88   0  15   4]
 [  0   0   0 152   0   0   3   0   3   0]
 [  0  15 

E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           1       0.00      0.00      0.00       135
           2       0.00      0.00      0.00       145
           3       0.00      0.00      0.00       104
           4       0.50      0.97      0.66       147
           5       0.17      0.01      0.03       141
           6       0.86      0.70      0.77       152
           7       0.19      0.81      0.30       147
           8       0.00      0.00      0.00        69
           9       0.29      0.20      0.24       142
          10       0.44      0.45      0.45       139

   micro avg       0.35      0.35      0.35      1321
   macro avg       0.25      0.31      0.24      1321
weighted avg       0.27      0.35      0.27      1321

0.3489780469341408
Confusion matrix, without normalization
[[  0   3   0  24   3   4  67   0  30   4]
 [  0   0   0   0   0   0 144   0   0   1]
 [  0   0   0  20   1   3  73   0   7   0]
 [  0   0   0 143   0   0   4   0   0   0]
 [  0  13 

E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           1       0.00      0.00      0.00       104
           2       0.00      0.00      0.00       138
           3       0.00      0.00      0.00       110
           4       0.52      0.98      0.68       150
           5       0.17      0.01      0.02       154
           6       0.85      0.72      0.78       138
           7       0.18      0.80      0.29       147
           8       0.00      0.00      0.00        72
           9       0.30      0.20      0.24       144
          10       0.44      0.37      0.40       164

   micro avg       0.35      0.35      0.35      1321
   macro avg       0.25      0.31      0.24      1321
weighted avg       0.27      0.35      0.27      1321

0.34519303557910674
Confusion matrix, without normalization
[[  0   1   0  16   2   2  55   0  26   2]
 [  0   0   0   1   0   0 135   0   1   1]
 [  2   1   0  16   1   1  77   0   9   3]
 [  0   0   0 147   1   0   0   0   2   0]
 [  0  13

E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           1       0.50      0.01      0.02       111
           2       0.00      0.00      0.00       131
           3       0.00      0.00      0.00       102
           4       0.50      0.98      0.66       130
           5       0.18      0.01      0.02       159
           6       0.83      0.70      0.76       162
           7       0.22      0.82      0.35       172
           8       0.00      0.00      0.00        73
           9       0.26      0.22      0.24       131
          10       0.42      0.38      0.40       150

   micro avg       0.36      0.36      0.36      1321
   macro avg       0.29      0.31      0.24      1321
weighted avg       0.32      0.36      0.28      1321

0.3557910673732021
Confusion matrix, without normalization
[[  1   4   0  12   2   1  58   0  27   6]
 [  0   0   0   0   0   0 130   0   1   0]
 [  1   3   0  12   0   4  68   0  12   2]
 [  0   0   0 127   0   0   1   0   2   0]
 [  0  17 

E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           1       0.50      0.01      0.02       126
           2       0.00      0.00      0.00       142
           3       0.00      0.00      0.00       116
           4       0.52      0.98      0.68       149
           5       0.00      0.00      0.00       155
           6       0.76      0.67      0.71       130
           7       0.19      0.80      0.31       155
           8       0.00      0.00      0.00        75
           9       0.28      0.22      0.24       134
          10       0.44      0.42      0.43       139

   micro avg       0.34      0.34      0.34      1321
   macro avg       0.27      0.31      0.24      1321
weighted avg       0.28      0.34      0.25      1321

0.3368660105980318
Confusion matrix, without normalization
[[  1   4   0  14   1   2  69   0  30   5]
 [  0   0   0   0   0   0 140   0   1   1]
 [  1   3   0  19   0   2  79   0   9   3]
 [  0   0   0 146   0   0   0   0   3   0]
 [  0  25 

E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           1       0.00      0.00      0.00       131
           2       0.00      0.00      0.00       146
           3       0.00      0.00      0.00       118
           4       0.50      0.99      0.66       141
           5       0.14      0.01      0.01       179
           6       0.80      0.70      0.74       125
           7       0.18      0.81      0.30       148
           8       0.00      0.00      0.00        69
           9       0.29      0.17      0.21       147
          10       0.32      0.41      0.36       117

   micro avg       0.32      0.32      0.32      1321
   macro avg       0.22      0.31      0.23      1321
weighted avg       0.23      0.32      0.23      1321

0.3186979560938683
Confusion matrix, without normalization
[[  0   1   0  23   0   1  71   0  29   6]
 [  0   0   0   0   0   0 145   0   0   1]
 [  1   1   0  18   0   3  80   0  11   4]
 [  0   0   0 140   0   0   0   0   1   0]
 [  0  20 

E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           1       0.00      0.00      0.00       121
           2       0.00      0.00      0.00       150
           3       0.00      0.00      0.00       108
           4       0.49      0.98      0.65       137
           5       0.00      0.00      0.00       152
           6       0.90      0.68      0.77       142
           7       0.21      0.88      0.34       156
           8       0.00      0.00      0.00        74
           9       0.39      0.18      0.25       161
          10       0.35      0.46      0.40       120

   micro avg       0.34      0.34      0.34      1321
   macro avg       0.23      0.32      0.24      1321
weighted avg       0.25      0.34      0.26      1321

0.34216502649507946
Confusion matrix, without normalization
[[  0   1   0  21   0   1  47   0  35  16]
 [  0   0   0   0   0   0 150   0   0   0]
 [  1   3   0  15   0   2  75   0   1  11]
 [  0   0   0 134   0   0   2   0   1   0]
 [  0  20

E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           1       0.00      0.00      0.00       116
           2       0.00      0.00      0.00       127
           3       0.00      0.00      0.00       103
           4       0.47      0.99      0.63       140
           5       0.20      0.01      0.01       155
           6       0.86      0.67      0.76       147
           7       0.18      0.77      0.29       148
           8       0.00      0.00      0.00        77
           9       0.31      0.17      0.22       162
          10       0.36      0.36      0.36       146

   micro avg       0.33      0.33      0.33      1321
   macro avg       0.24      0.30      0.23      1321
weighted avg       0.27      0.33      0.25      1321

0.3285389856169568
Confusion matrix, without normalization
[[  0   1   0  22   0   3  57   0  30   3]
 [  0   0   0   1   0   0 126   0   0   0]
 [  0   0   0  20   0   4  71   0   3   5]
 [  0   0   0 139   0   0   1   0   0   0]
 [  0  20 

E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           1       0.00      0.00      0.00       129
           2       0.00      0.00      0.00       138
           3       0.00      0.00      0.00       124
           4       0.52      0.97      0.68       158
           5       0.12      0.02      0.03       129
           6       0.80      0.73      0.76       139
           7       0.16      0.78      0.26       129
           8       0.00      0.00      0.00        79
           9       0.25      0.14      0.18       157
          10       0.35      0.36      0.36       139

   micro avg       0.32      0.32      0.32      1321
   macro avg       0.22      0.30      0.23      1321
weighted avg       0.24      0.32      0.25      1321

0.32475397426192276
Confusion matrix, without normalization
[[  0   2   0  17   1   5  63   0  32   9]
 [  0   0   0   0   0   0 138   0   0   0]
 [  5   2   0  19   2   7  78   0   7   4]
 [  0   0   0 153   0   0   4   0   1   0]
 [  0  12

E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
E:\Anacondaa\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [24]:
# 输出N次的平均准确率
avgscore = avgscore / N
recallscore = recallscore / N
precisionscore = precisionscore / N

print('avgscore....')
print(avgscore)
print('False positive rate')
print(1-precisionscore)
print('false negative rate')
print(1-recallscore)

avgscore....
0.3399697199091597
False positive rate
0.7491687404756171
false negative rate
0.6922009828695788
