In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
from sklearn import tree
from sklearn.linear_model import LinearRegression
from scipy import stats
import pylab as pl
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, recall_score, precision_score
import math
from sklearn.datasets.samples_generator import make_blobs
from sklearn.svm import SVC



In [2]:
# GIST特征值
subfeatures = pd.read_csv(r'E:\test\process_gist2\gist_f_train_full.csv',header=None)
labels = pd.read_csv(r'E:\test\process_gist2\CNO_full.txt',header=None)
print(subfeatures)

       0    1    2        3    4    5    6         7    8    9    ...  502  \
0      NaN  NaN  NaN      NaN  NaN  NaN  NaN       NaN  NaN  NaN  ...  NaN   
1      NaN  NaN  NaN  0.23956  NaN  NaN  NaN  0.237630  NaN  NaN  ...  NaN   
2      NaN  NaN  NaN      NaN  NaN  NaN  NaN       NaN  NaN  NaN  ...  NaN   
3      NaN  NaN  NaN  0.18744  NaN  NaN  NaN  0.440850  NaN  NaN  ...  NaN   
4      NaN  NaN  NaN      NaN  NaN  NaN  NaN       NaN  NaN  NaN  ...  NaN   
5      NaN  NaN  NaN  0.31370  NaN  NaN  NaN  0.401330  NaN  NaN  ...  NaN   
6      NaN  NaN  NaN      NaN  NaN  NaN  NaN       NaN  NaN  NaN  ...  NaN   
7      NaN  NaN  NaN  0.33926  NaN  NaN  NaN  0.308770  NaN  NaN  ...  NaN   
8      NaN  NaN  NaN  0.32031  NaN  NaN  NaN  0.239320  NaN  NaN  ...  NaN   
9      NaN  NaN  NaN  0.16760  NaN  NaN  NaN  0.245140  NaN  NaN  ...  NaN   
10     NaN  NaN  NaN  0.25577  NaN  NaN  NaN  0.327910  NaN  NaN  ...  NaN   
11     NaN  NaN  NaN  0.40402  NaN  NaN  NaN  0.350880  NaN  NaN

In [3]:
# 对全NaN列行进行清除
result = pd.concat([subfeatures, labels], axis=1,ignore_index=True)
# print(result)
result=result.dropna(how='all',axis=1)
result=result.dropna(how='any',axis=0)
result=result.reindex()
# print(result)
subfeatures=result.iloc[:,:-1]
labels=result.iloc[:,-1]
# print(subfeatures,'\n',labels)

In [4]:
# 平均准确率归零
avgscore = 0
recallscore = 0
precisionscore = 0
N = 10


In [5]:
# 进行十次SVM_Tree测试
for i in range(N):
    # 以10%的比例进行交叉验证
    # X_train, X_test, y_train, y_test = cross_validation.train_test_split(subfeatures, features_labels, test_size=0.1)
    X_train, X_test, y_train, y_test = train_test_split(subfeatures, labels, test_size=0.1)

    # 进行训练
    print('train...')
    # 进行SVC训练 使用线性核
    # clf = SVC(kernel='linear')                     # 高斯核 rbf
    clf = tree.DecisionTreeClassifier()
    clf.fit(X_train.values, y_train.values.reshape(len(y_train)))

    # 预试
    print('test...')
    c_test = clf.predict(X_test.values)

    # print(y_test)
    # print(c_test)

    # 计算预测划分准确率
    print('accurary...')
    score = clf.score(X_test.values, y_test.values.reshape(len(y_test)))
    print(classification_report(y_test, c_test))
    avgscore = avgscore + score
    recallscore = recallscore + recall_score(y_test, c_test, average="macro")
    precisionscore = precisionscore + precision_score(y_test, c_test, average="macro")
    print(score)

    # 通过混淆矩阵进行结果标示
    cm = confusion_matrix(y_test, c_test)
    np.set_printoptions(threshold=10000)
    np.set_printoptions(precision=2)
    print('Confusion matrix, without normalization')
    print(str(cm))



train...
test...
accurary...
              precision    recall  f1-score   support

           1       0.54      0.43      0.48       137
           2       0.74      0.86      0.79       121
           3       0.71      0.70      0.71       122
           4       0.46      0.44      0.45       138
           5       0.99      0.99      0.99       141
           6       0.97      0.98      0.97        91
           7       0.89      0.90      0.90       146
           8       0.91      0.97      0.94        70
           9       0.76      0.81      0.78       129
          10       0.77      0.76      0.77       144

   micro avg       0.77      0.77      0.77      1239
   macro avg       0.77      0.78      0.78      1239
weighted avg       0.76      0.77      0.76      1239

0.768361581920904
Confusion matrix, without normalization
[[ 59   8  16  33   0   0   2   2  10   7]
 [  2 104   1   7   0   0   1   0   2   4]
 [  7   3  86  10   1   0   3   3   2   7]
 [ 23  12   7  61   0   0

test...
accurary...
              precision    recall  f1-score   support

           1       0.46      0.43      0.45       120
           2       0.81      0.83      0.82       151
           3       0.72      0.76      0.74       111
           4       0.54      0.51      0.52       134
           5       0.96      0.98      0.97        98
           6       0.97      0.98      0.97        92
           7       0.84      0.88      0.86       160
           8       0.95      0.94      0.95        86
           9       0.74      0.71      0.73       140
          10       0.80      0.81      0.80       147

   micro avg       0.77      0.77      0.77      1239
   macro avg       0.78      0.78      0.78      1239
weighted avg       0.77      0.77      0.77      1239

0.7715899919289749
Confusion matrix, without normalization
[[ 52   7  11  20   0   1   9   0   9  11]
 [  2 125   3  11   0   0   2   2   2   4]
 [  7   3  84  10   0   0   3   0   2   2]
 [ 19   8   8  68   1   0   6   2

In [6]:
# 输出N次的平均准确率
avgscore = avgscore / N
recallscore = recallscore / N
precisionscore = precisionscore / N

print('avgscore....')
print(avgscore)
print('False positive rate')
print(1-precisionscore)
print('false negative rate')
print(1-recallscore)

avgscore....
0.7727199354317998
False positive rate
0.2238523327026083
false negative rate
0.21616048830988532
